In [1]:
import numpy as np
#
from sudoku_solver import SudokuSolver
from sudoku import Sudoku
from utils import timeout

In [2]:
s = Sudoku()

In [3]:
random_grid = s.random_grid()
random_grid

array([[1, 2, 3, 4, 9, 6, 5, 7, 8],
       [4, 5, 6, 1, 7, 8, 3, 2, 9],
       [7, 8, 9, 2, 3, 5, 1, 4, 6],
       [2, 1, 5, 3, 6, 7, 8, 9, 4],
       [3, 4, 7, 8, 1, 9, 2, 6, 5],
       [6, 9, 8, 5, 2, 4, 7, 1, 3],
       [5, 3, 1, 6, 4, 2, 9, 8, 7],
       [9, 6, 2, 7, 8, 3, 4, 5, 1],
       [8, 7, 4, 9, 5, 1, 6, 3, 2]])

In [4]:
s.random_seed

array([[0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0]])

In [5]:
s.grid

array([[1, 2, 3, 4, 9, 6, 5, 7, 8],
       [4, 5, 6, 1, 7, 8, 3, 2, 9],
       [7, 8, 9, 2, 3, 5, 1, 4, 6],
       [2, 1, 5, 3, 6, 7, 8, 9, 4],
       [3, 4, 7, 8, 1, 9, 2, 6, 5],
       [6, 9, 8, 5, 2, 4, 7, 1, 3],
       [5, 3, 1, 6, 4, 2, 9, 8, 7],
       [9, 6, 2, 7, 8, 3, 4, 5, 1],
       [8, 7, 4, 9, 5, 1, 6, 3, 2]])

In [6]:
s.randomize_token()

array([[3, 6, 1, 9, 4, 8, 2, 5, 7],
       [9, 2, 8, 3, 5, 7, 1, 6, 4],
       [5, 7, 4, 6, 1, 2, 3, 9, 8],
       [6, 3, 2, 1, 8, 5, 7, 4, 9],
       [1, 9, 5, 7, 3, 4, 6, 8, 2],
       [8, 4, 7, 2, 6, 9, 5, 3, 1],
       [2, 1, 3, 8, 9, 6, 4, 7, 5],
       [4, 8, 6, 5, 7, 1, 9, 2, 3],
       [7, 5, 9, 4, 2, 3, 8, 1, 6]])

In [7]:
s.token

array([0, 3, 6, 1, 9, 2, 8, 5, 7, 4])